# TODO: add high high-availability support
- name: Download k3s installer
  become: true
  ansible.builtin.get_url:
    url: https://get.k3s.io
    dest: /tmp/k3s_install.sh
    mode: "0755"
  when: inventory_hostname == groups['servers'][0]

- name: Install k3s agent
  become: true
  ansible.builtin.command: /tmp/k3s_install.sh
  args:
    creates: /usr/local/bin/k3s
  environment:
    K3S_URL: "https://{{ hostvars[groups['k3s_servers'][0]].ansible_host }}:6443"
    K3S_TOKEN: "{{ hostvars[groups['k3s_servers'][0]].k3s_servers_token }}"
  no_log: true

- name: Wait for agent node to be ready
  become: true
  ansible.builtin.command: >
    kubectl --kubeconfig /etc/rancher/k3s/k3s.yaml
    get node {{ inventory_hostname }}
    -o jsonpath='{.status.conditions[?(@.type=="Ready")].status}'
  delegate_to: "{{ groups['k3s_servers'][0] }}"
  register: k3s_agents_node_ready
  until: k3s_agents_node_ready.stdout.strip() == "True"
  retries: 10
  delay: 10
  changed_when: false
